import type { ActDefinition } from '../../types/game'
import streetImg from '../../assets/backgrounds/street.jpeg'
import standImg from '../../assets/backgrounds/stand.jpeg'
import alleyImg from '../../assets/backgrounds/alley.jpeg'

export const act1: ActDefinition = {
  id: 1,
  title: 'The Stand',
  titleZh: '台北街頭',
  tagline: 'Rain on the windshield, pink neon on the glass. The last delivery of the night is never the last.',
  cardGradient: 'linear-gradient(160deg, #07070f 0%, #1a0b22 60%, #4a0e33 100%)',
  glyph: '檳',
  defaultBg: 'street',
  gateDescription: 'Earn Brother Long’s interest — he only invites the useful and the steady.',
  backgrounds: {
    street: {
      gradient: 'linear-gradient(180deg, #0d0d1d 0%, #16162e 55%, #3d1030 100%)',
      glyph: '夜',
      label: 'Wanxia District · 11:47 PM',
      imageUrl: streetImg,
    },
    stand: {
      gradient: 'linear-gradient(180deg, #150a1e 0%, #33102e 50%, #7a1244 100%)',
      glyph: '檳',
      label: 'Twin Star Betel Nut · 雙星檳榔',
      imageUrl: standImg,
    },
    alley: {
      gradient: 'linear-gradient(180deg, #0a0a14 0%, #1c1226 60%, #3a1030 100%)',
      glyph: '巷',
      imageUrl: alleyImg,
      label: 'The alley behind the stand',
    },
  },
  start: 'intro1',
  nodes: {
    intro1: {
      id: 'intro1',
      kind: 'narration',
      bg: 'street',
      text: 'Taipei, a Tuesday night. You have been driving since five in the morning — vegetables to Yonghe, machine parts to Xizhi, and now an empty flatbed and a wet street in Wanxia District. Your shoulders ache. Your thermos is empty.',
      next: 'intro2',
    },
    intro2: {
      id: 'intro2',
      kind: 'narration',
      text: 'Across the road, a glass booth burns pink against the dark — 雙星檳榔, Twin Star Betel Nut. Neon tubes buzz like insects. Behind the glass, a young woman in a silver jacket is restocking a cooler, moving like she owns the whole street.',
      next: 'approach',
    },
    approach: {
      id: 'approach',
      kind: 'choice',
      prompt: 'The engine ticks as it cools. What do you do?',
      options: [
        { label: 'Walk up to the stand', next: 'greet' },
        { label: 'Stay in the truck and watch the street a while', next: 'stay1' },
      ],
    },
    stay1: {
      id: 'stay1',
      kind: 'narration',
      text: 'You watch. Scooters hiss past on the wet asphalt. Twice, black sedans slow in front of the stand without stopping — and the woman in silver clocks every plate without moving her head. Interesting corner.',
      next: 'stay2',
    },
    stay2: {
      id: 'stay2',
      kind: 'narration',
      text: 'Your stomach growls. There’s nothing else open, and something about that pink light pulls at you like a hook.',
      next: 'greet',
    },
    greet: {
      id: 'greet',
      kind: 'line',
      bg: 'stand',
      speaker: 'ahmei',
      text: '哎唷 — a customer with two feet instead of two wheels. You lost, driver, or just hungry?',
      next: 'ahmei_talk',
    },
    ahmei_talk: {
      id: 'ahmei_talk',
      kind: 'ai',
      character: 'ahmei',
      opener: 'We got mild, we got strong, we got the kind that keeps you awake to Kaohsiung. So — what does a tired man want tonight?',
      sceneContext:
        'Night at the Twin Star betel nut stand in Wanxia District, Taipei. The player is a tired truck driver who just finished a delivery and walked up to the glass booth. First meeting, low stakes, playful. Ah-Mei is bored and enjoys sizing up a new face. She warms to honesty, humor, and being treated like a person; she cools fast at sleaze or pity. She may drop small hints that this street "belongs" to certain people.',
      suggestions: [
        'First time buying. What do you recommend?',
        'Long night. I just needed to talk to another human being.',
        'This corner of yours sees a lot of traffic for midnight, huh?',
      ],
      minTurns: 2,
      exitLabel: 'Pay and step back',
      next: 'after_ahmei',
      gate: { minTrust: 30, failNext: 'ahmei_brush' },
    },
    ahmei_brush: {
      id: 'ahmei_brush',
      kind: 'line',
      speaker: 'ahmei',
      text: '哎唷, that all you got, 帥哥? The glass is thick but it isn’t THAT thick. Try talking to me like a person.',
      next: 'ahmei_brush2',
    },
    ahmei_brush2: {
      id: 'ahmei_brush2',
      kind: 'narration',
      text: 'She turns to restock a shelf, but there’s no real dismissal in it. The neon hums. The night is long, and so is her patience — barely.',
      next: 'ahmei_talk',
    },
    after_ahmei: {
      id: 'after_ahmei',
      kind: 'effects',
      effects: { cash: -100, charm: 3 },
      note: 'You pay for a pack you didn’t really want. The betel nut is bitter, then warm. Talking to her loosened something in your chest.',
      next: 'long_arrives',
    },
    long_arrives: {
      id: 'long_arrives',
      kind: 'narration',
      text: 'Headlights sweep the booth. A black sedan stops — not slowing, stopping. A man steps out: mid-forties, golf shirt, a watch that costs more than your truck. Ah-Mei’s smile goes professional. The man looks at you the way a butcher looks at a pig.',
      next: 'long_line1',
    },
    long_line1: {
      id: 'long_line1',
      kind: 'line',
      bg: 'alley',
      speaker: 'long',
      text: 'That Hino flatbed across the road. Yours? Walk with me a minute. I don’t like talking in the light.',
      next: 'long_talk',
    },
    long_talk: {
      id: 'long_talk',
      kind: 'ai',
      character: 'long',
      opener: 'Six axles of nothing, midnight, Wanxia. You’re either lost or looking for something. Which is it, 少年仔?',
      sceneContext:
        "Brother Long has pulled the player into the alley beside the Twin Star stand. He noticed the player's truck — the organization always needs drivers it can trust with cargo it can't insure. This is a job interview disguised as small talk. He tests nerve, discretion, and usefulness with sideways questions. He raises trust for plain, steady, useful answers and quiet nerve; he drops it hard for bragging, flattery, nervous rambling, or asking too many questions about the business. If trust gets high he begins hinting at 'an operation down south' worth seeing.",
      suggestions: [
        'I drive. Anywhere, any hour, no questions.',
        'Depends who’s asking.',
        'Six years on the southern routes. Never lost a load, never met a cop I couldn’t bore to death.',
      ],
      minTurns: 3,
      exitLabel: 'Wait for his verdict',
      next: 'long_invite',
      gate: { minTrust: 35, failNext: 'long_lowtrust' },
    },
    long_lowtrust: {
      id: 'long_lowtrust',
      kind: 'narration',
      text: '信任不足 — not enough trust. Long studies you like unfinished paperwork. He needs 35 trust before this goes anywhere. The conversation isn’t over.',
      next: 'long_talk',
    },
    long_reject: {
      id: 'long_reject',
      kind: 'line',
      speaker: 'long',
      text: 'Hm. Go home, driver. Wanxia eats the undecided.',
      next: 'reject_beat',
    },
    reject_beat: {
      id: 'reject_beat',
      kind: 'narration',
      text: 'He turns back toward the sedan, unhurried. The neon buzzes. Something tells you this door only opens once more — if at all.',
      next: 'retry_choice',
    },
    retry_choice: {
      id: 'retry_choice',
      kind: 'choice',
      prompt: 'He hasn’t reached the car yet.',
      options: [
        { label: 'Call after him — you’re not done talking', next: 'long_talk' },
        { label: 'Ask Ah-Mei about him first', next: 'ahmei_hint' },
      ],
    },
    ahmei_hint: {
      id: 'ahmei_hint',
      kind: 'line',
      bg: 'stand',
      speaker: 'ahmei',
      text: 'That’s Brother Long. 拍謝, free advice, one time only: he hates flattery and he hates chatter. Answer him straight, show him you’re useful, and never ask what’s in the boxes.',
      next: 'hint_back',
    },
    hint_back: {
      id: 'hint_back',
      kind: 'narration',
      bg: 'alley',
      text: 'You cross back to the alley. Long is standing by the car, lighting a cigarette. He watches you come — and waits.',
      next: 'long_talk',
    },
    long_invite: {
      id: 'long_invite',
      kind: 'line',
      speaker: 'long',
      text: 'Tomorrow. Five in the morning, before the city wakes up. There’s a farm in the south that grows money on trees — come see the operation. Don’t be late, and don’t tell anyone whose name you don’t know.',
      next: 'invite_fx',
    },
    invite_fx: {
      id: 'invite_fx',
      kind: 'effects',
      effects: { reputation: 10 },
      note: 'He didn’t shake your hand. Men like him don’t. But the invitation lands in your chest like a key turning.',
      logLine: 'Act 1 — Earned Brother Long’s invitation to the southern operation.',
      next: 'a1_end',
    },
    a1_end: {
      id: 'a1_end',
      kind: 'endAct',
    },
  },
}
