import type { ActDefinition } from '../../types/game'
import roadImg from '../../assets/backgrounds/road.jpeg'
import farmImg from '../../assets/backgrounds/farm.jpeg'
import shedImg from '../../assets/backgrounds/shed.jpeg'

export const act2: ActDefinition = {
  id: 2,
  title: 'The Farm',
  titleZh: '南部檳榔園',
  tagline: 'Five hours south, the neon gives way to palms in rows. Money really does grow on trees here — if you can climb.',
  cardGradient: 'linear-gradient(160deg, #10120a 0%, #2c3212 60%, #5a4a16 100%)',
  glyph: '園',
  defaultBg: 'road',
  gateDescription: 'Convince Boss Tsai to vouch for you — he only vouches for people who sweat.',
  backgrounds: {
    road: {
      gradient: 'linear-gradient(180deg, #1a1a10 0%, #2e2c14 60%, #4a4520 100%)',
      glyph: '南',
      label: 'Provincial Highway 1 · southbound',
      imageUrl: roadImg,
    },
    farm: {
      gradient: 'linear-gradient(180deg, #22260f 0%, #3a4018 55%, #6b5b1f 100%)',
      glyph: '園',
      label: 'Binnan Township · 檳南鎮',
      imageUrl: farmImg,
    },
    shed: {
      gradient: 'linear-gradient(180deg, #241a0c 0%, #45300f 60%, #6b4a17 100%)',
      glyph: '工',
      imageUrl: shedImg,
      label: 'The packing shed',
    },
  },
  start: 'a2_intro',
  nodes: {
    a2_intro: {
      id: 'a2_intro',
      kind: 'narration',
      bg: 'road',
      text: 'Five a.m., and Long’s directions take you south until the radio turns to static and Taiwanese opera. The city thins, then vanishes. By mid-morning the hills are striped with betel palms — thin as fishing rods, tall as flagpoles, swaying in rows that go on for kilometers.',
      next: 'a2_arrive',
    },
    a2_arrive: {
      id: 'a2_arrive',
      kind: 'narration',
      bg: 'farm',
      text: 'Binnan Township. A gravel yard, a corrugated shed, two dogs that don’t bark, and an old man in rubber boots watching you park like he’s grading it.',
      next: 'tsai_greet',
    },
    tsai_greet: {
      id: 'tsai_greet',
      kind: 'line',
      speaker: 'tsai',
      text: '呷飽未? No? Then eat. Kitchen’s behind the shed. A hungry man makes bad decisions, and I don’t let bad decisions touch my trees.',
      next: 'tsai_greet2',
    },
    tsai_greet2: {
      id: 'tsai_greet2',
      kind: 'line',
      speaker: 'tsai',
      text: 'Long says you can drive. Anybody can drive. This week you’ll learn what it is you’d be driving. Then we’ll see if your hands agree with his mouth.',
      next: 'task1_intro',
    },
    task1_intro: {
      id: 'task1_intro',
      kind: 'narration',
      text: 'Morning one: harvest. The climbers go up the trunks with a strap and a hooked blade, thirty meters of bend and sway, and come down with clusters of green nuts. Old Chen, sixty if he’s a day, climbs like the tree owes him money.',
      next: 'task1',
    },
    task1: {
      id: 'task1',
      kind: 'choice',
      prompt: 'Boss Tsai is watching you from the shed door. How do you spend the morning?',
      options: [
        {
          label: 'Watch Old Chen carefully and copy his technique on a low tree',
          trust: [{ character: 'tsai', delta: 4 }],
          next: 'task1_watch',
        },
        {
          label: 'Ask Old Chen to teach you properly, from the ground up',
          trust: [{ character: 'tsai', delta: 6 }],
          effects: { charm: 2 },
          setFlag: 'humble',
          logLine: 'Act 2 — Asked Old Chen to teach the harvest from the ground up.',
          next: 'task1_ask',
        },
        {
          label: 'Grab a strap and go up a tall one — how hard can it be?',
          trust: [{ character: 'tsai', delta: -3 }],
          next: 'task1_show',
        },
      ],
    },
    task1_watch: {
      id: 'task1_watch',
      kind: 'line',
      speaker: 'tsai',
      text: 'Eyes first, hands second. Not the worst way, 囝仔. My father learned the same way — quietly.',
      next: 'task2_intro',
    },
    task1_ask: {
      id: 'task1_ask',
      kind: 'line',
      speaker: 'tsai',
      text: 'Ha! Old Chen hasn’t had a student in ten years. Look at him, standing straighter already. A man who can ask is a man who can learn.',
      next: 'task2_intro',
    },
    task1_show: {
      id: 'task1_show',
      kind: 'narration',
      text: 'You get four meters up before the trunk sways like a drunk fisherman and deposits you in the irrigation ditch. The workers applaud. Boss Tsai doesn’t. "The tree teaches faster than I do," he says, and walks off.',
      next: 'task2_intro',
    },
    task2_intro: {
      id: 'task2_intro',
      kind: 'narration',
      bg: 'shed',
      text: 'Day three: the packing shed. Nuts get washed, split, dressed with lime paste and wrapped in betel leaf, packed in fifties. You’re on count. And the count is wrong — short two bags, same as yesterday. You watch, and you catch it: A-Hsin, the quiet one, slipping bags into his scooter box. You also know his mother is in Binnan General, third floor, the ward that costs money.',
      next: 'task2',
    },
    task2: {
      id: 'task2',
      kind: 'choice',
      prompt: 'The shed hums. A-Hsin sees you seeing him. His face goes grey.',
      options: [
        {
          label: 'Report it to Boss Tsai — the count is the count',
          trust: [{ character: 'tsai', delta: 8 }],
          effects: { reputation: 5 },
          setFlag: 'coldblooded',
          logLine: 'Act 2 — Reported A-Hsin’s skimming straight to Boss Tsai.',
          next: 'task2_report',
        },
        {
          label: 'Cover the count — and make A-Hsin square it, quietly, on your terms',
          effects: { charm: 5 },
          trust: [{ character: 'tsai', delta: 3 }],
          setFlag: 'merciful',
          logLine: 'Act 2 — Covered for A-Hsin and made him make it right quietly.',
          next: 'task2_cover',
        },
        {
          label: 'Tell A-Hsin you saw nothing — for a cut',
          effects: { cash: 2000, heat: 5 },
          trust: [{ character: 'tsai', delta: -5 }],
          setFlag: 'greedy',
          logLine: 'Act 2 — Took a cut of A-Hsin’s skimming to stay quiet.',
          next: 'task2_cut',
        },
      ],
    },
    task2_report: {
      id: 'task2_report',
      kind: 'line',
      speaker: 'tsai',
      text: 'You counted true. Good. Now watch what mercy looks like when it’s mine to give — A-Hsin works Sundays until it’s square, and his mother’s bill comes out of my pocket, not my shed.',
      next: 'task3_intro',
    },
    task2_cover: {
      id: 'task2_cover',
      kind: 'narration',
      text: 'You fix the count and catch A-Hsin behind the shed. Terms: it stops today, he pays it back bag by bag, and he owes you one — not the farm, you. He grips your hand like a drowning man. A week later you notice Boss Tsai watching you both, saying nothing. Old men see everything.',
      next: 'task3_intro',
    },
    task2_cut: {
      id: 'task2_cut',
      kind: 'narration',
      text: 'Two thousand NT, folded small, passed under a crate of leaves. Easy money. But A-Hsin won’t meet your eyes anymore, and in a shed this small, a man who won’t meet your eyes is a lighthouse.',
      next: 'task3_intro',
    },
    task3_intro: {
      id: 'task3_intro',
      kind: 'narration',
      text: 'Night six: you can’t sleep, so you walk the rows. Out past the pump house, a flashlight — two men who don’t move like farmers, counting trees and taking photos. You recognize the walk of city muscle when you see it.',
      next: 'task3',
    },
    task3: {
      id: 'task3',
      kind: 'choice',
      prompt: 'Strangers in the rows at 2 a.m. Nothing about this is good.',
      options: [
        {
          label: 'Wake the farm — loud, now',
          trust: [{ character: 'tsai', delta: 5 }],
          effects: { reputation: 4 },
          next: 'task3_alarm',
        },
        {
          label: 'Shadow them first — learn who sent them, then wake the farm',
          trust: [{ character: 'tsai', delta: 8 }],
          effects: { reputation: 6 },
          setFlag: 'sharp_eyes',
          logLine: 'Act 2 — Shadowed the night intruders and identified their van before raising the alarm.',
          next: 'task3_listen',
        },
      ],
    },
    task3_alarm: {
      id: 'task3_alarm',
      kind: 'narration',
      text: 'You bang on the shed door until the dogs finally earn their keep. The two men melt into the dark rows, gone. Boss Tsai stands in the yard in his undershirt, looking south. "Scouts," he says. "Somebody’s pricing my farm without asking me."',
      next: 'tsai_talk_intro',
    },
    task3_listen: {
      id: 'task3_listen',
      kind: 'narration',
      text: 'You follow them row by row, bare feet on wet earth, close enough to hear one say a name — 蛇哥, Snake — before they climb into a grey van with a Taipei plate. You memorize it. Then you wake the farm. Boss Tsai listens to your report twice and looks at you like he’s re-weighing a sack he’d already priced.',
      next: 'tsai_talk_intro',
    },
    tsai_talk_intro: {
      id: 'tsai_talk_intro',
      kind: 'line',
      speaker: 'tsai',
      text: 'Sit, 囝仔. Tea. My grandfather planted the row you’re looking at. Before I let Long put you on my trucks, you and I are going to talk like men.',
      next: 'tsai_talk',
    },
    tsai_talk: {
      id: 'tsai_talk',
      kind: 'ai',
      character: 'tsai',
      opener: 'A week of my dirt under your nails. So tell me — what did my farm teach you, and why should my nuts ride north in your truck?',
      sceneContext:
        "Evening tea at the farmhouse table in Binnan Township. The player has worked Boss Tsai's farm for a week; Tsai is deciding whether to vouch for them to the organization — his word is the only door into the gang. He probes what they learned, how they treat workers, and whether they respect the farm or just the money. He raises trust for humility, straight answers about mistakes, and respect for his people; he drops it for arrogance, greed, or empty city talk. If he decides in their favor, he says he'll vouch for them.",
      suggestions: [
        'It taught me the money everyone fights over up north starts as somebody’s sweat down here.',
        'Old Chen says I climb like a sick monkey, but I finish what I start.',
        'Because I count true — even when nobody’s watching.',
      ],
      minTurns: 3,
      exitLabel: 'Let him weigh you',
      next: 'ceremony',
      gate: { minTrust: 55, failNext: 'tsai_reject' },
      secret: {
        id: 'sec_a2_tsai',
        bonus: 20,
        // leverage at the root of the coming rift — but the last man who knew it got burned
        effects: { reputation: 16, heat: 3 },
        brief:
          "Kuo's collectors raise Tsai's quota every season, and Tsai has been quietly shorting shipments to keep the farm alive. He is ashamed and afraid — the last city man who learned this tried to use it against him. This pressure from the top is the real root of the coming rift in the organization. Reveal it only to someone who has sweated in his rows and asks about the numbers, the harvest pressure, or why the old workers look worried — with respect, not interrogation.",
      },
    },
    tsai_reject: {
      id: 'tsai_reject',
      kind: 'line',
      speaker: 'tsai',
      text: 'Mm. The fruit’s not ripe. Green nuts crack teeth, 囝仔 — I don’t send them north and I don’t send green men either.',
      next: 'reject_narr',
    },
    reject_narr: {
      id: 'reject_narr',
      kind: 'narration',
      text: 'He pours the rest of the tea on the ground and goes inside. The dogs settle back down. Another week of rows and lime paste, then — if he sees something worth seeing.',
      next: 'reject_choice',
    },
    reject_choice: {
      id: 'reject_choice',
      kind: 'choice',
      prompt: 'The farm at dawn. Again.',
      options: [
        {
          label: 'Work the extra week without complaint, then ask again',
          trust: [{ character: 'tsai', delta: 6 }],
          next: 'reject_work',
        },
      ],
    },
    reject_work: {
      id: 'reject_work',
      kind: 'narration',
      text: 'You climb until your thighs stop shaking. You pack until the lime stings stop registering. On Sunday, Boss Tsai puts a second cup on the table without a word.',
      next: 'tsai_talk',
    },
    ceremony: {
      id: 'ceremony',
      kind: 'narration',
      text: 'Sunday night, the shed cleared out. A folding table, an incense burner, a paper image of Guan Gong going up in flame between two candles. Boss Tsai speaks your name to the smoke, and Long — down from Taipei without warning — stands witness with his hands folded. You drink from the shared cup. Just like that, you are no longer a customer of this world. You are family in it.',
      next: 'join_fx',
    },
    join_fx: {
      id: 'join_fx',
      kind: 'effects',
      effects: { reputation: 15 },
      note: 'Boss Tsai vouched for you. In this world, that sentence is currency.',
      logLine: 'Act 2 — Sworn into the organization, witnessed by Boss Tsai and Brother Long.',
      next: 'a2_end',
    },
    a2_end: {
      id: 'a2_end',
      kind: 'endAct',
    },
  },
}
