import type { ActDefinition } from '../../types/game'
import highwayImg from '../../assets/backgrounds/highway.jpeg'
import reststopImg from '../../assets/backgrounds/reststop.jpeg'
import warehouseImg from '../../assets/backgrounds/warehouse.jpeg'

export const act3: ActDefinition = {
  id: 3,
  title: 'The Runs',
  titleZh: '北上運輸',
  tagline: 'Three hundred kilometers of dark highway between the farm and the neon. Every kilometer wants something from you.',
  cardGradient: 'linear-gradient(160deg, #04050b 0%, #101830 60%, #23355c 100%)',
  glyph: '路',
  defaultBg: 'highway',
  gateDescription: 'Reputation 50+ — Long only shares the truth with proven earners.',
  backgrounds: {
    highway: {
      gradient: 'linear-gradient(180deg, #05060d 0%, #0e1526 55%, #1d2b4a 100%)',
      glyph: '路',
      label: 'Provincial Highway 1 · northbound, 2 a.m.',
      imageUrl: highwayImg,
    },
    reststop: {
      gradient: 'linear-gradient(180deg, #0c0a14 0%, #221230 55%, #4a1a3c 100%)',
      glyph: '站',
      label: 'Highway rest stop · sodium lights',
      imageUrl: reststopImg,
    },
    warehouse: {
      gradient: 'linear-gradient(180deg, #0a0a14 0%, #181a2e 60%, #2a2545 100%)',
      glyph: '倉',
      imageUrl: warehouseImg,
      label: 'The Sanchong warehouse',
    },
  },
  start: 'a3_intro',
  nodes: {
    a3_intro: {
      id: 'a3_intro',
      kind: 'narration',
      bg: 'warehouse',
      text: 'The work is simple the way a knife is simple. Betel nut spoils in days — the farms cut and pack at dusk, and the trucks run north through the night so the stands can sell fresh at dawn. You get a route, a loading dock in Sanchong, and a phone that only ever shows one name: 龍哥.',
      next: 'long_check1',
    },
    long_check1: {
      id: 'long_check1',
      kind: 'ai',
      character: 'long',
      opener: 'First run tonight. Forty crates, Binnan to Sanchong, gate three. Questions? Good drivers have exactly one or none.',
      sceneContext:
        "The Sanchong warehouse, before the player's first official run as a made member. Long is now the player's handler. Businesslike briefing; he answers one good practical question well and shuts down chatter. He respects drivers who focus on the work.",
      suggestions: [
        'One question: if a checkpoint stops me, whose name do I not say?',
        'No questions. Gate three, before dawn.',
        'What’s the cargo worth, so I know what I’m protecting?',
      ],
      minTurns: 1,
      exitLabel: 'Take the keys',
      next: 'run1_intro',
      gate: { minTrust: 70, failNext: 'long_check1_lowtrust' },
    },
    long_check1_lowtrust: {
      id: 'long_check1_lowtrust',
      kind: 'narration',
      text: '信任不足 — not enough trust. Long doesn’t hand the keys over. He needs 70 trust before you drive his cargo. Keep talking.',
      next: 'long_check1',
    },
    run1_intro: {
      id: 'run1_intro',
      kind: 'narration',
      bg: 'highway',
      text: 'Run one. Rain again. Two hundred kilometers in, orange cones squeeze the highway to one lane — a police checkpoint, torches waving. Forty crates of fresh-cut betel nut behind you, and paperwork that says "vegetables."',
      next: 'run1',
    },
    run1: {
      id: 'run1',
      kind: 'choice',
      prompt: 'The sergeant strolls toward your window, unhurried, like a man who owns the hour.',
      options: [
        {
          label: 'Slip him the envelope Long gave you "for weather like this"',
          effects: { cash: -3000, reputation: 3 },
          logLine: 'Act 3 — Paid off the checkpoint sergeant, clean and quiet.',
          next: 'run1_bribe',
        },
        {
          label: 'Talk vegetables, yawn, complain about the market prices',
          requiresStat: { stat: 'charm', min: 28 },
          effects: { reputation: 8, charm: 2 },
          logLine: 'Act 3 — Talked a checkpoint sergeant to sleep. Cargo never opened.',
          next: 'run1_talk',
        },
        {
          label: 'Gun it through the coned lane before he reaches the window',
          effects: { reputation: 12, heat: 15 },
          logLine: 'Act 3 — Ran a police checkpoint with forty crates aboard.',
          next: 'run1_run',
        },
      ],
    },
    run1_bribe: {
      id: 'run1_bribe',
      kind: 'narration',
      text: 'The envelope vanishes into a rain jacket like a magic trick. "Drive safe," the sergeant says, already waving the next truck through. Expensive weather. But quiet.',
      next: 'run2_intro',
    },
    run1_talk: {
      id: 'run1_talk',
      kind: 'narration',
      text: 'You give him five full minutes on cabbage futures and the tragedy of cold-chain logistics. His eyes glaze at minute two. He waves you through at minute five just to make it stop. In the mirror you allow yourself one grin.',
      next: 'run2_intro',
    },
    run1_run: {
      id: 'run1_run',
      kind: 'narration',
      text: 'The engine roars, cones scatter, a torch beam whips across your mirrors. By the time the radio chatter catches up, you’re three exits gone with your plates swapped at a dark rest stop. The cargo arrives on time. So does the story — and stories travel both up and down.',
      next: 'run2_intro',
    },
    run2_intro: {
      id: 'run2_intro',
      kind: 'narration',
      bg: 'reststop',
      text: 'Run two, a week later. You pull into the usual rest stop to swap manifests — and three scooters slide in behind the truck like eels. Rival crew. Young, loud, bats across their laps. Their leader taps your fender: "Road tax, brother. New management."',
      next: 'run2',
    },
    run2: {
      id: 'run2',
      kind: 'choice',
      prompt: 'Three of them, one of you, forty crates that spoil by noon.',
      options: [
        {
          label: 'Step down from the cab holding the tire iron — slowly',
          effects: { reputation: 12, heat: 10 },
          logLine: 'Act 3 — Faced down three rival collectors with a tire iron at the rest stop.',
          next: 'run2_fight',
        },
        {
          label: 'Pay the "tax" — tonight the cargo matters more than pride',
          effects: { cash: -2000, reputation: 4 },
          logLine: 'Act 3 — Paid a rival crew’s road tax to keep the run on schedule.',
          next: 'run2_pay',
        },
        {
          label: 'Smile, reverse out, and take the old mountain road instead',
          effects: { reputation: 8 },
          logLine: 'Act 3 — Ghosted a rival ambush via the old mountain road.',
          next: 'run2_detour',
        },
      ],
    },
    run2_fight: {
      id: 'run2_fight',
      kind: 'narration',
      text: 'You don’t swing it. You just set it on your shoulder and ask which of them wants to explain to their boss why forty crates of Kuo’s product got dented. The word "Kuo" does the work the iron doesn’t have to. They leave. Your hands shake for fifty kilometers, but nobody sees that part.',
      next: 'heat_check',
    },
    run2_pay: {
      id: 'run2_pay',
      kind: 'narration',
      text: 'Two thousand NT for three grins and a fender tap. The cargo makes gate three by 4 a.m. Long says nothing when you report it — which is its own kind of grade.',
      next: 'heat_check',
    },
    run2_detour: {
      id: 'run2_detour',
      kind: 'narration',
      text: 'The mountain road is two lanes of fog, monkeys, and one shrine with a red light that watches you pass. You lose ninety minutes and gain a route nobody else will drive. The stands get their nuts by six. Long files that fact away somewhere behind his eyes.',
      next: 'heat_check',
    },
    heat_check: {
      id: 'heat_check',
      kind: 'gate',
      check: (s) => s.stats.heat < 70,
      passNext: 'run3_intro',
      failNext: 'shakedown',
    },
    shakedown: {
      id: 'shakedown',
      kind: 'narration',
      text: 'Too much noise, too fast. Two plainclothes are waiting at your usual noodle stall — not to arrest you, to price you. It costs an envelope thick enough to hurt before they remember other appointments.',
      next: 'shakedown_fx',
    },
    shakedown_fx: {
      id: 'shakedown_fx',
      kind: 'effects',
      effects: { cash: -5000, heat: -20 },
      note: 'NT$5,000 lighter, considerably less famous. Heat fades. Lesson lingers.',
      logLine: 'Act 3 — Paid off plainclothes cops after drawing too much heat.',
      next: 'run3_intro',
    },
    run3_intro: {
      id: 'run3_intro',
      kind: 'narration',
      bg: 'highway',
      text: 'Run three. At the Hsinchu fuel stop, a soft-spoken man in a golf cap "admires your cargo." He runs stands in the science park — off the network. He’ll take twenty percent of tonight’s load, cash, right now, and nobody up north needs to learn arithmetic.',
      next: 'run3',
    },
    run3: {
      id: 'run3',
      kind: 'choice',
      prompt: 'NT$8,000, folded once, resting on the diesel pump between you.',
      options: [
        {
          label: 'Take the deal — shrinkage happens on every farm',
          effects: { cash: 8000, heat: 8 },
          trust: [{ character: 'long', delta: -8 }],
          setFlag: 'side_dealer',
          logLine: 'Act 3 — Sold 20% of a shipment off-book at the Hsinchu fuel stop.',
          next: 'run3_take',
        },
        {
          label: 'Refuse — and remember his face for the organization',
          effects: { reputation: 10 },
          trust: [{ character: 'long', delta: 5 }],
          logLine: 'Act 3 — Refused an off-book buyer and reported him to Long.',
          next: 'run3_refuse',
        },
      ],
    },
    run3_take: {
      id: 'run3_take',
      kind: 'narration',
      text: 'Eight crates change trucks in four minutes. The manifest develops a water stain exactly where a number used to be. Weeks later, Long mentions — apropos of nothing — that the farm’s counts and the warehouse’s counts had a disagreement. He watches your face while he says it.',
      next: 'pay_fx',
    },
    run3_refuse: {
      id: 'run3_refuse',
      kind: 'narration',
      text: 'You pocket nothing and memorize everything: plate, cap, the mole on his jaw. Long listens to your description twice, writes nothing down, and buys your noodles. From him, that’s a medal.',
      next: 'pay_fx',
    },
    pay_fx: {
      id: 'pay_fx',
      kind: 'effects',
      effects: { cash: 12000 },
      note: 'Three runs’ pay, cash, rubber-banded. The stack is starting to feel normal in your hand. That should worry you more than it does.',
      next: 'gate_rep',
    },
    gate_rep: {
      id: 'gate_rep',
      kind: 'gate',
      check: (s) => s.stats.reputation >= 50,
      passNext: 'long_final_intro',
      failNext: 'makeup_intro',
    },
    makeup_intro: {
      id: 'makeup_intro',
      kind: 'narration',
      bg: 'warehouse',
      text: 'Long meets you at gate three with a clipboard and a verdict: "Not yet. The brothers upstairs count in stories, and yours is still short a chapter." There’s work on the board for a driver who wants a name.',
      next: 'makeup',
    },
    makeup: {
      id: 'makeup',
      kind: 'choice',
      prompt: 'The board has two jobs nobody wants.',
      options: [
        {
          label: 'The night convoy — three trucks, no radio, you lead',
          effects: { reputation: 15, heat: 8, cash: 4000 },
          logLine: 'Act 3 — Led the three-truck night convoy through the coast road.',
          next: 'makeup_out',
        },
        {
          label: 'The double shift — Binnan to Sanchong twice in one night',
          effects: { reputation: 12, heat: 3, cash: 3000 },
          logLine: 'Act 3 — Ran the Binnan double shift on no sleep.',
          next: 'makeup_out',
        },
      ],
    },
    makeup_out: {
      id: 'makeup_out',
      kind: 'narration',
      text: 'You deliver. Again. The warehouse crew has started calling you 拚命 — "the one who doesn’t die." Names like that climb stairs by themselves.',
      next: 'gate_rep',
    },
    long_final_intro: {
      id: 'long_final_intro',
      kind: 'line',
      bg: 'reststop',
      speaker: 'long',
      text: 'Sit. Eat. The beef noodle here is the only honest thing on this highway. Tonight I’m going to talk more than I like, so don’t waste it.',
      next: 'long_final',
    },
    long_final: {
      id: 'long_final',
      kind: 'ai',
      character: 'long',
      opener: 'You’ve earned a real name upstairs. So you should know what upstairs looks like: Big Brother Kuo is getting old, and old kings tax the farms harder every season to feel young. Snake Hsu smells it. Things will move soon, 少年仔 — and everyone will have to stand somewhere.',
      sceneContext:
        "A late-night noodle stall on the highway. Long, the player's handler, is being uncharacteristically open: the organization is splitting. Big Brother Kuo is aging and paranoid, squeezing Boss Tsai's farms with higher quotas; Snake Hsu, an ambitious lieutenant, is quietly building his own faction. Long is loyal to the organization itself, not to any one man, and he is testing whether the player understands loyalty, patience, and timing. He respects careful questions and honest uncertainty here; he distrusts eager scheming or naive loyalty oaths.",
      suggestions: [
        'Where do you stand, 龍哥?',
        'And the farms? Boss Tsai vouched for me. I don’t forget that.',
        'I’m a driver. Tell me the route and I’ll drive it.',
      ],
      minTurns: 2,
      exitLabel: 'Finish the noodles',
      next: 'a3_end_fx',
      gate: { minTrust: 90, failNext: 'long_final_lowtrust' },
    },
    long_final_lowtrust: {
      id: 'long_final_lowtrust',
      kind: 'narration',
      text: '信任不足 — not enough trust. Long goes quiet and orders more noodles. A man doesn’t share the top of the mountain with someone he trusts less than 90. Keep talking.',
      next: 'long_final',
    },
    a3_end_fx: {
      id: 'a3_end_fx',
      kind: 'effects',
      effects: { reputation: 5 },
      note: 'Long paid for the noodles and left first — but he left you the good seat, the one facing the door. In this world, furniture is a language.',
      logLine: 'Act 3 — Long confided the rift at the top of the organization.',
      next: 'a3_end',
    },
    a3_end: {
      id: 'a3_end',
      kind: 'endAct',
    },
  },
}
